### ISSUE TITLE
scoreboard counter filter isn't working

### ISSUE THREAD

**Issue by racterub** [racterub/tyshscore-web#16]
url: `http://0.0.0.0:6969/scoreboard/20`

counter checker: https://github.com/racterub/tyshscore-web/blob/74bcd957449cf5397de1340793a566a79ceb010d/website/views/main.py#L52

it somehow passed to parser.....
which will cause index out of range

**Comment by racterub** [comment]
Trace:
```
Traceback (most recent call last):
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macintosh/github/tyshscore-web/website/views/main.py", line 60, in scoreboard
    body.append(i[counter-1])
IndexError: list index out of range
```

**Comment by racterub** [comment]
Fixed.
