### ISSUE TITLE
PARSER BROKEN

### ISSUE THREAD

**Issue by racterub** [racterub/tyshscore-web#29]
Stacktrace:
```
Traceback (most recent call last):
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macintosh/.venv/tysh/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macintosh/github/tyshscore-web/website/views/main.py", line 80, in scoreboard
    exam_score, below_subject = get_term_score()
  File "/Users/macintosh/github/tyshscore-web/website/views/lib/crawler.py", line 86, in get_term_score
    j[k] = float(j[k])
ValueError: could not convert string to float: '◎ 統整數學Ⅱ'
```

Due to school-end will dymatically change the layout of the scoreboard, there are some lines of bug listed as follows:
- https://github.com/racterub/tyshscore-web/blob/2ea6dc53040f01786475fcaf64e421282b2d2f5d/website/views/lib/crawler.py#L70 
	- Hardcoded list value
- https://github.com/racterub/tyshscore-web/blob/2ea6dc53040f01786475fcaf64e421282b2d2f5d/website/views/lib/crawler.py#L78
	- Hardcoded chunk size
- https://github.com/racterub/tyshscore-web/blob/2ea6dc53040f01786475fcaf64e421282b2d2f5d/website/views/lib/crawler.py#L79-L91
	- Needs to remake due to this issue

FOR NOW THIS APP WILL NOT WORK FOR 3rd GRADE STUDENTS.

**Comment by racterub** [comment]
THIS IS THE FINAL ISSUE FOR MILESTONE 1.x
